_target_: navsim.common.dataclasses.SceneFilter
_convert_: 'all'

num_history_frames: 4
num_future_frames: 10
frame_interval: 1
has_route: true

max_scenes: null
log_names:
  - '2021.06.03.12.02.06_veh-35_01100_01227'
  - '2021.09.09.17.18.51_veh-48_01462_01552'
  - '2021.06.28.15.02.02_veh-38_02398_02848'
  - '2021.06.03.12.02.06_veh-35_00233_00609'
  - '2021.05.25.15.59.03_veh-30_04027_04200'
  - '2021.06.03.13.55.17_veh-35_02572_02855'
  - '2021.09.16.13.53.10_veh-42_00180_00342'
  - '2021.05.25.14.16.10_veh-35_02482_02649'
  - '2021.09.29.14.44.26_veh-28_00238_00320'
  - '2021.05.25.14.24.08_veh-25_04059_04203'
  - '2021.05.25.17.54.41_veh-35_01654_01850'
  - '2021.09.16.15.47.30_veh-45_01199_01391'
  - '2021.05.25.14.24.08_veh-25_00934_01067'
  - '2021.09.09.18.29.25_veh-39_00969_01184'
  - '2021.10.06.08.16.17_veh-52_00922_01296'
  - '2021.05.25.16.37.23_veh-25_00005_00217'
  - '2021.06.03.17.06.58_veh-35_03860_03992'
  - '2021.09.16.13.53.10_veh-42_00860_01069'
  - '2021.06.28.18.03.27_veh-14_00620_01581'
  - '2021.09.16.16.20.27_veh-08_02435_02525'
  - '2021.05.25.18.38.25_veh-25_04058_04186'
  - '2021.09.09.17.18.51_veh-48_00574_00646'
  - '2021.06.03.17.06.58_veh-35_00712_00855'
  - '2021.06.03.13.55.17_veh-35_00073_00426'
  - '2021.09.16.14.39.34_veh-42_01609_01687'
  - '2021.09.09.17.18.51_veh-48_01173_01237'
  - '2021.09.09.18.29.25_veh-39_01622_01766'
  - '2021.09.29.18.19.40_veh-28_00844_01218'
  - '2021.10.06.08.16.17_veh-52_00181_00574'
  - '2021.10.06.07.26.10_veh-52_00772_00917'
  - '2021.09.09.18.29.25_veh-39_00569_00903'
  - '2021.10.06.08.16.17_veh-52_00032_00170'
  - '2021.06.03.18.47.39_veh-35_00503_00777'
  - '2021.05.25.14.16.10_veh-35_01100_01664'
  - '2021.10.06.08.16.17_veh-52_01590_01725'
  - '2021.06.28.20.24.43_veh-38_00369_00601'
  - '2021.09.29.14.44.26_veh-28_00528_00992'
  - '2021.06.28.15.10.57_veh-16_02438_02580'
  - '2021.10.06.07.26.10_veh-52_00953_01126'
  - '2021.10.06.07.26.10_veh-52_01245_02064'
  - '2021.09.16.19.49.00_veh-42_00990_01609'
  - '2021.09.29.15.23.04_veh-28_00601_00802'
  - '2021.06.03.13.55.17_veh-35_02419_02561'
  - '2021.09.29.18.19.40_veh-28_00331_00426'
  - '2021.09.16.19.12.04_veh-42_01438_01677'
  - '2021.08.30.13.45.25_veh-40_01116_01336'
  - '2021.09.09.18.29.25_veh-39_00427_00556'
  - '2021.09.16.14.39.34_veh-42_01111_01448'
  - '2021.06.03.17.06.58_veh-35_02943_03220'
  - '2021.09.29.19.02.14_veh-28_00540_00917'
  - '2021.06.28.16.29.11_veh-38_01415_01821'
  - '2021.09.09.17.18.51_veh-48_00657_00876'
  - '2021.09.16.19.27.01_veh-45_01749_03230'
  - '2021.05.25.14.16.10_veh-35_04097_04328'
  - '2021.09.16.19.27.01_veh-45_00472_00711'
  - '2021.05.25.15.59.03_veh-30_03499_03671'
  - '2021.08.30.16.16.44_veh-40_01099_01351'
  - '2021.09.29.19.02.14_veh-28_02911_03005'
  - '2021.08.30.13.45.25_veh-40_00878_01104'
  - '2021.09.16.19.12.04_veh-42_00289_00398'
  - '2021.05.25.14.16.10_veh-35_00083_00485'
  - '2021.09.29.18.19.40_veh-28_01727_01833'
  - '2021.09.09.17.18.51_veh-48_00098_00328'
  - '2021.09.09.14.18.22_veh-48_00221_00299'
  - '2021.09.09.18.04.06_veh-40_00555_00731'
  - '2021.09.16.15.12.03_veh-42_01037_01434'
  - '2021.06.03.13.55.17_veh-35_00789_00999'
  - '2021.06.03.18.47.39_veh-35_00257_00492'
  - '2021.09.09.17.18.51_veh-48_01248_01450'
  - '2021.09.09.14.18.22_veh-48_01298_01492'
  - '2021.06.28.13.53.26_veh-26_00492_00696'
  - '2021.05.25.15.59.03_veh-30_04463_04606'
  - '2021.08.30.16.16.44_veh-40_00779_01088'
  - '2021.06.28.16.29.11_veh-38_03263_03766'
  - '2021.09.16.14.39.34_veh-42_00297_00935'
  - '2021.09.16.13.53.10_veh-42_00077_00153'
  - '2021.10.06.08.16.17_veh-52_01949_02501'
  - '2021.05.25.16.37.23_veh-25_03311_03550'
  - '2021.06.28.20.24.43_veh-38_03385_04952'
  - '2021.09.29.19.02.14_veh-28_00964_01689'
  - '2021.09.29.14.44.26_veh-28_01331_01485'
  - '2021.09.16.13.53.10_veh-42_01510_01591'
  - '2021.06.03.18.47.39_veh-35_00123_00246'
  - '2021.10.06.08.16.17_veh-52_01430_01579'
  - '2021.09.29.19.02.14_veh-28_00273_00514'
  - '2021.09.29.19.02.14_veh-28_02451_02708'
  - '2021.10.06.07.26.10_veh-52_00422_00728'
  - '2021.09.16.13.53.10_veh-42_00630_00818'
  - '2021.08.16.14.23.37_veh-45_00015_00132'
  - '2021.08.30.13.45.25_veh-40_00784_00867'
  - '2021.09.16.19.12.04_veh-42_01088_01192'
  - '2021.08.30.14.54.34_veh-40_00439_00835'
  - '2021.09.09.14.18.22_veh-48_01503_01761'
  - '2021.06.28.16.57.59_veh-26_00016_00484'
  - '2021.06.28.21.47.53_veh-35_00280_00424'
  - '2021.10.06.07.26.10_veh-52_00006_00398'
  - '2021.09.29.15.23.04_veh-28_00814_01101'
  - '2021.05.25.14.26.37_veh-27_04122_04279'
  - '2021.09.09.18.04.06_veh-40_01340_01425'
  - '2021.05.25.14.24.08_veh-25_03764_04034'
  - '2021.05.25.17.54.41_veh-35_01905_02121'
  - '2021.09.09.17.18.51_veh-48_00889_01147'
  - '2021.09.29.14.44.26_veh-28_01509_01628'
  - '2021.05.25.15.59.03_veh-30_00625_00855'
  - '2021.05.25.17.54.41_veh-35_04967_05098'
  - '2021.09.09.18.04.06_veh-40_00743_01071'
  - '2021.05.25.17.54.41_veh-35_02723_02902'
  - '2021.08.30.14.54.34_veh-40_00885_00986'
  - '2021.05.25.15.59.03_veh-30_01478_01643'
  - '2021.05.25.14.16.10_veh-35_01690_02183'
  - '2021.09.09.14.18.22_veh-48_00322_00895'
  - '2021.06.28.16.29.11_veh-38_00022_00368'
  - '2021.09.16.19.12.04_veh-42_01221_01380'
  - '2021.08.30.13.45.25_veh-40_00610_00771'
  - '2021.09.29.14.44.26_veh-28_01059_01191'
  - '2021.09.29.14.44.26_veh-28_01640_01743'
  - '2021.09.29.19.02.14_veh-28_03198_03360'
  - '2021.08.30.14.54.34_veh-40_00334_00419'
  - '2021.09.16.14.39.34_veh-42_00032_00186'
  - '2021.09.29.14.44.26_veh-28_00337_00504'
  - '2021.06.03.13.55.17_veh-35_02866_03582'
  - '2021.06.03.17.06.58_veh-35_02571_02742'
  - '2021.10.06.08.16.17_veh-52_00612_00782'
  - '2021.09.29.19.02.14_veh-28_01717_01824'
  - '2021.06.28.21.16.05_veh-14_00957_01198'
  - '2021.09.29.18.19.40_veh-28_01268_01685'
  - '2021.09.16.17.40.09_veh-45_02539_02745'
  - '2021.09.09.14.18.22_veh-48_00960_01115'
  - '2021.09.29.14.44.26_veh-28_01202_01296'
  - '2021.10.06.07.26.10_veh-52_02208_02394'
  - '2021.09.29.18.19.40_veh-28_00438_00833'
  - '2021.06.03.12.02.06_veh-35_03526_03712'
  - '2021.08.30.16.16.44_veh-40_00256_00716'
  - '2021.09.16.21.13.37_veh-42_00172_00347'
  - '2021.05.25.17.54.41_veh-35_04111_04288'
  - '2021.05.25.14.16.10_veh-35_03373_03550'

tokens:
  - '5798a6e25f2553e4'
  - '3dc6b109b480502f'
  - 'a4f2f32aa59f53b9'
  - '9164913b818a58b1'
  - '713c5a168c2452dc'
  - '1975d15fde2955ff'
  - 'b27bfe84cc545daa'
  - '57730912486a5853'
  - 'b111bb8716b756d2'
  - 'e11f2ff7ffba5b45'
  - 'b7ee1af184835990'
  - '3789d42ea83f569d'
  - 'e9bb1dab462252e9'
  - '5ad18b7f7b2a52c7'
  - 'e0bb2b04e9455fa6'
  - '1ebfee14fc925d6e'
  - 'd2789ec30aaa5d6a'
  - '0d5b8da00d505be0'
  - '8be5c83488ff5980'
  - '871164a7e40652b5'
  - '8a8bf2275db85432'
  - '9bdf0d338d625e2a'
  - '43cc094e7af0518e'
  - '21747e180852591a'
  - '440364f63ee95043'
  - '82e565141eb55f88'
  - 'd7ff11915cdf538e'
  - '23d0ae8aedf8537b'
  - 'afe269451bc757e1'
  - '0f3d66a03c5e500b'
  - 'c49e7550cee75722'
  - 'db817c126780531f'
  - '3ec484ccad125e99'
  - '7602906d3c785da3'
  - '8cafe946e9c752fc'
  - '10209c0e885f5162'
  - '586c5b66ad8158ee'
  - '8c2e3aa977d95da5'
  - 'b2f320b5d94753f9'
  - 'ce3ff067f10b526b'
  - 'b86152f6ab29580e'
  - '7bbb6cfc4f135e50'
  - '5a06f03022ec5b67'
  - '662212c87d0d5b09'
  - 'dc952092ef6a5243'
  - '6227e5b0f0d4592e'
  - '4f21925f1a7c5983'
  - 'c5e8daf69c6552a7'
  - '627ed4c9950753e9'
  - '8781cde1032354cb'
  - '7444ae8aea51554e'
  - '2035406a3a6955be'
  - '263367576c285a2a'
  - '475a45837ca75030'
  - 'd5cf4595a3435917'
  - '7135ce0e5eea5907'
  - '17ecb960d15d5b5f'
  - 'a1e689b17ca65053'
  - '3b185264ec565b67'
  - '69616d6f715256dc'
  - 'd792515ce4b257a4'
  - '0f206a62842b59b2'
  - '19cee80b71525f86'
  - '96a0bbef8c335c3e'
  - '3ea2b59016145c63'
  - '8072e0c324205e72'
  - '0dfcc232f8445d3f'
  - '7e3ae733f7ef5c8f'
  - 'cab75d9e74eb52a1'
  - '9ecb516bac035ce4'
  - '77ee60147e0e55b7'
  - '7186e23637965344'
  - '484b6d9a28f350bd'
  - 'a82ce9edf79d56a6'
  - '81d6a870aab05080'
  - '5b61b9072cad5dbc'
  - '33aa90792d5855a7'
  - '13fcbcdacbe35755'
  - 'b39df49b8b565ac3'
  - 'd90d4f05ebde5bed'
  - 'ed1a1174e6aa5270'
  - '09779eb483435cab'
  - '7be2f6436ce95042'
  - '099ff4835ee45eb6'
  - '76dd2e9ad6f753b8'
  - 'a4c23fa815945fe3'
  - '50e871f60296566b'
  - '007845701f635565'
  - 'f3521da962a75e3d'
  - 'ce2de8af70e05a57'
  - 'fc1785d55b675c6c'
  - 'e3418fb50fa55320'
  - '5d058c203f765173'
  - '18a85f2812b45525'
  - '385e44b3382350f1'
  - 'a366d90f10ca5866'
  - '01b9125ad835592f'
  - 'e52c457d50455d0c'
  - '603d4a913f315a41'
  - '599e006109385ae5'
  - '683e518fbfa650d5'
  - '26e6818bd14d52a5'
  - '59159c92e5d9571d'
  - '09c56525e8e853a8'
  - 'a197927702b850f4'
  - 'd4849a52aaa55a9f'
  - 'b39406677030585e'
  - '8569121235665be9'
  - 'b3509fd31f495cfb'
  - 'eeb4b973450f50e9'
  - '137f854539c45fe1'
  - '62d339c4086d51ba'
  - 'fc2a5f9f60965ab9'
  - 'bdffdc5fc2fa542b'
  - '8bacfc35148b5dad'
  - '7bacd3cec5df553f'
  - '720c4f312c0f529e'
  - '685e5e9083185108'
  - '59cc5d51c60d5a1d'
  - 'dbb26055ea9351dc'
  - '0df6533b550c58c1'
  - '6b678e4f19c05dea'
  - '0490beca807c5e9f'
  - '05769097cb6c5b91'
  - '2601ffe0d2a056be'
  - 'b5d0bfdf09375423'
  - 'c15774bfb6655d18'
  - '06bdef9a9bbc5aaf'
  - '85005d733df9577f'
  - '8894cb9c1f385198'
  - 'bd4be260be50516f'
  - 'b4c5bd35a81f517e'
