_target_: navsim.common.dataclasses.SceneFilter
_convert_: 'all'

num_history_frames: 4
num_future_frames: 10
frame_interval: 1
has_route: true

max_scenes: null
log_names: null # list of log names to extract scenes from, if null, all logs are extracted
tokens:
 - 'ed4ac2dad0fa584b'
 - '2111b648fcba5bb7'
 - '1fc1dd0dc3d157ae'
 - '76a69c9e9e375670'
 - '4d3a4cbc9efb5337'
 - '06df05f607855dbf'
 - 'c3856d49ecf453f0'
 - '09d3f08395e05d1c'
 - '0593ddf8a1bb5a57'
 - 'c0b386ab15db56f9'
 - '0ef0f369529e54a9'
 - 'c754b1af814a5f23'
 - 'b214f8e744075e96'
 - '5cbacc029a9f5cb3'
 - 'cb46ac2ddfdf506e'
 - '108d77bad2275975'
 - '3978246a10a25ab0'
 - '41bb74b4738f5a8b'
 - '3a8375c20b615fce'
 - '82dc3fff070b5f80'
 - '8bfb2d59b82057e6'
 - 'e36d3626a55e54f9'
 - '5b1c0e44a5505c06'
 - '78e6ea95b854551c'
 - '76af8c24431855c3'
 - '1a84e817c1875ec6'
 - 'e7ea3ed9a30e5444'
 - '8c837572950a5ac0'
 - 'c18f8cfc41385d8c'
 - '11aa12f4e5715b08'
 - '702bdcfabe0755fe'
 - 'c11854507e515b05'
 - '828f0769bf365504'
 - '1d2d2ddbbd5450a4'
 - '640423c4ff21538a'
 - '93fa463a455857f6'
 - '79214a9a65225eda'
 - 'cd9d78a1011c555f'
 - '2a3f7fbaa10b5627'
 - '5abf2148971855ad'
 - 'd9200709d73756c3'
 - 'cf94200201a75af8'
 - 'c97bad66929c58d1'
 - 'e45b782c83a550c1'
 - 'e869951de22f5ecc'
 - '9610b02bc4ec529c'
 - '70ed6ff1471f5d74'
 - 'f8a971a1e94553ce'
 - '91e77e1873d75afe'
 - 'dc86b9a3e2e05466'
 - 'a3efdab7285751a6'
 - 'ecca4f25f1cd5a85'
 - '3c09e960d73758eb'
 - '58fb7f78e39451bc'
 - '0ce0aa336fe751a4'
 - '759d96676b965349'
 - 'e3b1564e52cd52db'
 - '48333fc684d454a2'
 - '62cae48b4e445254'
 - 'e97256ddafa85705'
 - '568aee30ea2655e2'
 - '2b8645e05e8854f0'
 - '1ce8022305ba565c'
 - 'fd3f8f3310255030'
 - 'f0b74302312b5241'
 - 'd74e1e5648e35864'
 - '5bff4e6fa9c95deb'
 - '97d3764b7be652cf'
 - 'de681a4826e35220'
 - 'be2540e76b10519d'
 - 'c7e91cc3157b5937'
 - '12a68a4c440c5396'
 - 'ac0c803827d65b80'
 - 'c18771a3868f5868'
 - 'a6340d3e28b95701'
 - '24fff541744b573f'
 - 'e7165cb777e65dac'
 - '7c1553e7080b5a70'
 - '6dffb4d149eb5089'
 - '0773a8971c5e5e5a'
 - '72dac45a812f56fb'
 - '75c16dc4849b5726'
 - '523eab76cc4653bd'
 - 'f246f785c3455caa'
 - 'baf59d54fb78575a'
 - 'b29743e5885f5514'
 - 'd213c35fc6055569'
 - '3ba8190534b1554c'
 - '26e297939af25760'
 - 'da643d2d70785c76'
 - '2137a540b5f05b48'
 - 'ed795a36682f5728'
 - '000afad751a95adb'
 - '7543fb2f2dcf5c7e'
 - '9b5c00687d4e590b'
 - '16d0a19acfcd5668'
 - 'd91da3c6f79b53f6'
 - '154694dd0f6c565c'
 - '9b4b3a0261595a47'
 - '0df3061f21f4502a'
 - '7e0b549208c75322'
 - '74678e95029e52a2'
 - '49196fecbe9a549f'
 - '0decaed8d0f45b26'
 - 'b3671d0ef61e5391'
 - '7b990d22090f5a21'
 - '4fea3406427a52de'
 - 'e7ac9da207d05a7f'
 - '69b772bf2aa15e8b'
 - '09300186157e51e9'
 - 'c61c26797b2d52f8'
 - 'eac8efd956975d88'
 - 'ad0ca9004c1e56c6'
 - '9c48c3a7714e5850'
 - '1bac9ad3b5795fb9'
 - '5dad11490b425565'
 - '1f6cea56be625f10'
 - 'f2fa70a966055b14'
 - '68520950dcca56d2'
 - 'e905af2fb80f5802'
 - 'e5445523551c573a'
 - '5a3b197e54495443'
 - '35d813d8de5854f9'
 - '25e0169687d659c0'
 - '88f7863088bc593e'
 - '06767022b8445e7f'
 - '4fcdad926f4a5568'
 - '8f5b483a5dd956d3'
 - 'a64cd79798845d53'
 - 'de864917fc075773'
 - '50418b03a9345e7f'
 - 'e991b5b1ef9d5fcd'
 - 'ea75df402b6a5d37'
 - '17b4e23eb78b547b'
 - '79388c5790cf5b02'
 - '7b9cc1b02566583e'
 - 'a8b415f811cb5bfa'
 - 'f4e49919c3d35a1a'
 - '79ca73b34554570a'
 - 'f9902a62c80c511a'
 - '71057951bf9a5e81'
 - '411cc15794895e1e'
 - '7c4fca218b0854d7'
 - '8498fd37028051b7'
 - '27decc74a57b53ac'
 - '50480a33ca215770'
 - '47f300be059c5734'
 - '70f2ea8358ed55f1'
 - '471f7ca3148659cd'
 - '4800f9f234c050fa'
 - '64c71ae3532a5efb'
 - '5e8f9f6ab5695769'
 - '2d9168675ce355a2'
 - '3c077c8da4615b33'
 - 'c7e8c07beb135247'
 - '2f8055010b905651'
 - '340d245e2ee854fe'
 - '70df39aae7b05204'
 - '388782e615ec5bba'
 - '7cb3886f8bb557d3'
 - 'b37a0e95ac4055ba'
 - '8be138812f1459d2'
 - '3ff2c6494d63527b'
 - '05fab28931d55ff9'
 - '333189d65a42540d'
 - '73bb3d277424505f'
 - 'cbe6088df42d55dc'
 - 'aa784b6564cb56a3'
 - 'cd30af3a16945a92'
 - 'c3a15b9f7dd55cce'
 - '44b6e898e157569a'
 - '4e4062c303565251'
 - 'd74f9dfdb4125eaf'
 - 'c0365ee92dec511d'
 - '4e98aff61c5e57b1'
 - '7200dcdd4ad05210'
 - 'c8124080125a5278'
 - '1586145ff7ae5b89'
 - '6b7f1a53f7d3524c'
 - '3bf37bad40c55175'
 - 'bdde0c029ec25326'
 - 'cd0a777bac035272'
 - '67b76696aa305cdc'
 - '614111a5d6045ae7'
 - 'f383acca25ff59eb'
 - 'cea15449dc0356bd'
 - 'b80387b22e0c55b5'
 - '065a0963a4125096'
 - 'c9e06d789998518d'
 - '4615024da7765d62'
 - 'ef336e8b83245733'
 - 'be4ec4d7ce745612'
 - '5169ec4362225b58'
 - 'c6f905906f9654a2'
 - '194216a5f85d592d'
 - '6529aed422f35336'
 - '497ac853176d59b6'
 - 'f280ba623a7f5321'
 - 'b5fe876937af504a'
 - 'c6b62c299ccc5274'
 - 'dcb2a35ae605510a'
 - 'd1c281e277d1532d'
 - '8f3366be46c05d5f'
 - 'af9f5f6fa1ad5182'
 - '5054593a6d795256'
 - '159b9b7451195c9c'
 - '7687f25bf8845686'
 - '560f3ccbaa5b53ef'
 - 'e5a146299341551a'
 - 'b794c616319352c3'
 - 'fb68b32ec8a251da'
 - '9fce6f03ef0351b0'
 - '046fd63cb514581a'
 - '0ce82a1caffc56af'
 - '7cc94c33bbe052d7'
 - 'b5126e9ddea25889'
 - 'c123273de19d5c2f'
 - 'df570b3785a95295'
 - 'a5efa651fec451b5'
 - '216f7065c13c5ec9'
 - '4754eb209bc452e4'
 - 'ce28728cdb6f50c9'
 - '33461776a24d554f'
 - '0920187661745605'
 - '0633cb3809935cb7'
 - 'f3e9317326955421'
 - '1c371291fdc1551a'
 - '37185bcf00de5be6'
 - '224510571ce95a3f'
 - 'e38a6e1fd4c55393'
 - '3a0b00f0840658e5'
 - '0d6abcbad24652c0'
 - '4789245424875682'
 - 'fba38dd9492a5341'
 - 'b649dcb158a75dcd'
 - '1a5182ccbf1b5955'
 - '1ac622ff2d2e5210'
 - 'f63cff56784d5cb9'
 - '0ea876c450bb5aa6'
 - '6fc06c6e4d1752a1'
 - '88396ca47dcf5361'
 - '7e1f829a0de95258'
 - '5f9a9890f1a75602'
 - '5a60c57493885588'
 - '67be2615438d55fb'
 - 'bda2fb6ea7735b5a'
 - '55aa596e131d5734'
 - 'd1a786625a885023'
 - '8ec0cd02d7705766'
 - 'e378bb756641598d'
 - 'c853ae7a361f54d9'
 - 'b1db6a099fea55f5'
 - 'ca8bc031163a5765'
 - 'eee8261221df5048'
 - 'b33131090ada5f2d'