_target_: navsim.common.dataclasses.SceneFilter
_convert_: all
num_history_frames: 4
num_future_frames: 10
frame_interval: 1
has_route: true
max_scenes: null
log_names:
- 2021.06.03.12.02.06_veh-35_01100_01227
- 2021.09.09.17.18.51_veh-48_01462_01552
- 2021.06.28.15.02.02_veh-38_02398_02848
- 2021.06.03.12.02.06_veh-35_00233_00609
- 2021.05.25.15.59.03_veh-30_04027_04200
- 2021.06.03.13.55.17_veh-35_02572_02855
- 2021.09.16.13.53.10_veh-42_00180_00342
- 2021.05.25.14.16.10_veh-35_02482_02649
- 2021.09.29.14.44.26_veh-28_00238_00320
- 2021.05.25.14.24.08_veh-25_04059_04203
- 2021.05.25.17.54.41_veh-35_01654_01850
- 2021.09.16.15.47.30_veh-45_01199_01391
- 2021.05.25.14.24.08_veh-25_00934_01067
- 2021.09.09.18.29.25_veh-39_00969_01184
- 2021.10.06.08.16.17_veh-52_00922_01296
- 2021.05.25.16.37.23_veh-25_00005_00217
- 2021.06.03.17.06.58_veh-35_03860_03992
- 2021.09.16.13.53.10_veh-42_00860_01069
- 2021.06.28.18.03.27_veh-14_00620_01581
- 2021.09.16.16.20.27_veh-08_02435_02525
- 2021.05.25.18.38.25_veh-25_04058_04186
- 2021.09.09.17.18.51_veh-48_00574_00646
- 2021.06.03.17.06.58_veh-35_00712_00855
- 2021.06.03.13.55.17_veh-35_00073_00426
- 2021.09.16.14.39.34_veh-42_01609_01687
- 2021.09.09.17.18.51_veh-48_01173_01237
- 2021.09.09.18.29.25_veh-39_01622_01766
- 2021.09.29.18.19.40_veh-28_00844_01218
- 2021.10.06.08.16.17_veh-52_00181_00574
- 2021.10.06.07.26.10_veh-52_00772_00917
- 2021.09.09.18.29.25_veh-39_00569_00903
- 2021.10.06.08.16.17_veh-52_00032_00170
- 2021.06.03.18.47.39_veh-35_00503_00777
- 2021.05.25.14.16.10_veh-35_01100_01664
- 2021.10.06.08.16.17_veh-52_01590_01725
- 2021.06.28.20.24.43_veh-38_00369_00601
- 2021.09.29.14.44.26_veh-28_00528_00992
- 2021.06.28.15.10.57_veh-16_02438_02580
- 2021.10.06.07.26.10_veh-52_00953_01126
- 2021.10.06.07.26.10_veh-52_01245_02064
- 2021.09.16.19.49.00_veh-42_00990_01609
- 2021.09.29.15.23.04_veh-28_00601_00802
- 2021.06.03.13.55.17_veh-35_02419_02561
- 2021.09.29.18.19.40_veh-28_00331_00426
- 2021.09.16.19.12.04_veh-42_01438_01677
- 2021.08.30.13.45.25_veh-40_01116_01336
- 2021.09.09.18.29.25_veh-39_00427_00556
- 2021.09.16.14.39.34_veh-42_01111_01448
- 2021.06.03.17.06.58_veh-35_02943_03220
- 2021.09.29.19.02.14_veh-28_00540_00917
- 2021.06.28.16.29.11_veh-38_01415_01821
- 2021.09.09.17.18.51_veh-48_00657_00876
- 2021.09.16.19.27.01_veh-45_01749_03230
- 2021.05.25.14.16.10_veh-35_04097_04328
- 2021.09.16.19.27.01_veh-45_00472_00711
- 2021.05.25.15.59.03_veh-30_03499_03671
- 2021.08.30.16.16.44_veh-40_01099_01351
- 2021.09.29.19.02.14_veh-28_02911_03005
- 2021.08.30.13.45.25_veh-40_00878_01104
- 2021.09.16.19.12.04_veh-42_00289_00398
- 2021.05.25.14.16.10_veh-35_00083_00485
- 2021.09.29.18.19.40_veh-28_01727_01833
- 2021.09.09.17.18.51_veh-48_00098_00328
- 2021.09.09.14.18.22_veh-48_00221_00299
- 2021.09.09.18.04.06_veh-40_00555_00731
- 2021.09.16.15.12.03_veh-42_01037_01434
- 2021.06.03.13.55.17_veh-35_00789_00999
- 2021.06.03.18.47.39_veh-35_00257_00492
- 2021.09.09.17.18.51_veh-48_01248_01450
- 2021.09.09.14.18.22_veh-48_01298_01492
- 2021.06.28.13.53.26_veh-26_00492_00696
- 2021.05.25.15.59.03_veh-30_04463_04606
- 2021.08.30.16.16.44_veh-40_00779_01088
- 2021.06.28.16.29.11_veh-38_03263_03766
- 2021.09.16.14.39.34_veh-42_00297_00935
- 2021.09.16.13.53.10_veh-42_00077_00153
- 2021.10.06.08.16.17_veh-52_01949_02501
- 2021.05.25.16.37.23_veh-25_03311_03550
- 2021.06.28.20.24.43_veh-38_03385_04952
- 2021.09.29.19.02.14_veh-28_00964_01689
- 2021.09.29.14.44.26_veh-28_01331_01485
- 2021.09.16.13.53.10_veh-42_01510_01591
- 2021.06.03.18.47.39_veh-35_00123_00246
- 2021.10.06.08.16.17_veh-52_01430_01579
- 2021.09.29.19.02.14_veh-28_00273_00514
- 2021.09.29.19.02.14_veh-28_02451_02708
- 2021.10.06.07.26.10_veh-52_00422_00728
- 2021.09.16.13.53.10_veh-42_00630_00818
- 2021.08.16.14.23.37_veh-45_00015_00132
- 2021.08.30.13.45.25_veh-40_00784_00867
- 2021.09.16.19.12.04_veh-42_01088_01192
- 2021.08.30.14.54.34_veh-40_00439_00835
- 2021.09.09.14.18.22_veh-48_01503_01761
- 2021.06.28.16.57.59_veh-26_00016_00484
- 2021.06.28.21.47.53_veh-35_00280_00424
- 2021.10.06.07.26.10_veh-52_00006_00398
- 2021.09.29.15.23.04_veh-28_00814_01101
- 2021.05.25.14.26.37_veh-27_04122_04279
- 2021.09.09.18.04.06_veh-40_01340_01425
- 2021.05.25.14.24.08_veh-25_03764_04034
- 2021.05.25.17.54.41_veh-35_01905_02121
- 2021.09.09.17.18.51_veh-48_00889_01147
- 2021.09.29.14.44.26_veh-28_01509_01628
- 2021.05.25.15.59.03_veh-30_00625_00855
- 2021.05.25.17.54.41_veh-35_04967_05098
- 2021.09.09.18.04.06_veh-40_00743_01071
- 2021.05.25.17.54.41_veh-35_02723_02902
- 2021.08.30.14.54.34_veh-40_00885_00986
- 2021.05.25.15.59.03_veh-30_01478_01643
- 2021.05.25.14.16.10_veh-35_01690_02183
- 2021.09.09.14.18.22_veh-48_00322_00895
- 2021.06.28.16.29.11_veh-38_00022_00368
- 2021.09.16.19.12.04_veh-42_01221_01380
- 2021.08.30.13.45.25_veh-40_00610_00771
- 2021.09.29.14.44.26_veh-28_01059_01191
- 2021.09.29.14.44.26_veh-28_01640_01743
- 2021.09.29.19.02.14_veh-28_03198_03360
- 2021.08.30.14.54.34_veh-40_00334_00419
- 2021.09.16.14.39.34_veh-42_00032_00186
- 2021.09.29.14.44.26_veh-28_00337_00504
- 2021.06.03.13.55.17_veh-35_02866_03582
- 2021.06.03.17.06.58_veh-35_02571_02742
- 2021.10.06.08.16.17_veh-52_00612_00782
- 2021.09.29.19.02.14_veh-28_01717_01824
- 2021.06.28.21.16.05_veh-14_00957_01198
- 2021.09.29.18.19.40_veh-28_01268_01685
- 2021.09.16.17.40.09_veh-45_02539_02745
- 2021.09.09.14.18.22_veh-48_00960_01115
- 2021.09.29.14.44.26_veh-28_01202_01296
- 2021.10.06.07.26.10_veh-52_02208_02394
- 2021.09.29.18.19.40_veh-28_00438_00833
- 2021.06.03.12.02.06_veh-35_03526_03712
- 2021.08.30.16.16.44_veh-40_00256_00716
- 2021.09.16.21.13.37_veh-42_00172_00347
- 2021.05.25.17.54.41_veh-35_04111_04288
- 2021.05.25.14.16.10_veh-35_03373_03550
tokens:
- e5b0b2c83a395163
- e6fd7389cbfb5943
- 9502cdbb06dd516f
- 88c0bfe353235280
- f9cfac7b9f30506d
- 0747dcc3a9b7501f
- 6b8b72c830b85a62
- afbf26b6d3bb5bee
- dfa220d6e64f5d84
- d58c4ad27c525465
- 9d423dea34235b41
- 7d99843a72555dd3
- 16e5aafc056f5e1e
- 4e734888d8465563
- 4cf809416df6527e
- fd513762a5ea5dd4
- c5099436d08c5e1f
- 277f191c94b952f3
- b66db24cee7957a2
- 866fab78f1da518b
- e0190f0059145fc6
- 0503cc398e2656be
- 19488eb3301f5d26
- 2649dcc8a1725fb2
- d6641a8596f25d47
- 9e7ae0e0f04255fa
- 8f5cefce0c0259d9
- dbb26055ea9351dc
- fc1785d55b675c6c
- 6e738f032ad75169
- 62c59eb9ece45d86
- 3e634fa2ea715bb1
- c41b4666b98e5b92
- ad0c441309de5d2e
- 06ea285b61b55a54
- fae7a01d5d815f04
- d35a0c5da0c55970
- 77155a60b2ae5e75
- 20d3a5f5b9e6549f
- cbda46701b0d57b8
- eee59dd716c05e1b
- 90c51d90c33b5cef
- 501de4adcf415443
- 7f3ebea7b3415f87
- 45d416b638f95a9c
- 0d93c2f3442752d9
- dc5bfa6f51225853
- 4d5a01dea92b5867
- 7d24bd01f77c5d87
- 29e7ffa0ba1f589b
- 7c8900e0a2ef5024
- 2a48beb84af65349
- 8b7212ba11ec5f3b
- 1d16c78634695b4a
- 66ba432a760c586c
- 026e84581e0f5044
- 38f1e14586bd51e3
- 2a04d84433e6576f
- cc853dd8697f51b3
- 253c33ffe10a5aa7
- 2c120899a8d05979
- 646244aaa99d5c9c
- 08ebfd6fbc145517
- ec372e5b0ad7504f
- 2c337eb368fb54ca
- 0751ef23000050f8
- 75151361dbe658bb
- 30422125ddd4590b
- e2c14ab1fbe350b1
- 607fd9c5903d5376
- b9148aabf55250e9
- 07bf0601ad425977
- 757fb1d7679c5dc2
- 64f47c2f2c7754cb
- 9147938e42675685
- 02d9591fc6de53c8
- 60021a9f6c585c16
- 1a4d88c3ccc6586d
- b874be1fb9885c0e
- bfb583c3969950ba
- fcbc81e3caa75186
- 2c0f41d407295efa
- 07dc9de3dd855653
- 305eb53245715f7e
- 1a6595a6c7cb5531
- 60dfaa1afc395c5d
- 8aec77f33ddb5ac8
- b958e6967993560f
- 1c064ec24fa15900
- 7140077d03e25c2c
- 4885d99d4c3959b8
- 2da6f8c86c135473
- 777328bf3a3d5e15
- da56fca2caff52e4
- 58d69daf413c5d5a
- 2a7b12a784c351c3
- c195a8cb7ccb59fd
- 2391f12d7e6a5e7f
- 33a43f22312c570d
- ccd53fdd1b6e51b8
- ec5e157a5222534d
- 9dd982b0637453c2
- 8f82805b2edb5a25
- ea34282dc63d5a9a
- c3907cc0d2ed5600
- 2c29f40d1a1d5b28
- 8b3bd35b8b945918
- 9147a0ae2bf751c8
- 03aa8a0576a25b63
- 2f5ae1e4cf9d59fa
- 78a46fe48bf15051
- 0d857e82084e56be
- 73872fdc28995ad6
- c16f84d1251552af
- 7cb9260c8be35c5c
- 50eebed7d9655bb5
- 72be63ed04f15f97
- 4ed57aa187415e7f
- 78b4153a6d3e5b33
- 7515bed58abd5f21
- 3be53588a286557f
- 2db50cd1c1ea5837
- 8e9c1bb8232c5a14
- bf1f3fe1ca935bba
- bd4be260be50516f
- 9090d50c08b05715
- 9568c56631be548e
- 7291b74b016d5672
- 0371700bf65b51e0
- c2eecf5cfe46536f
- 134cbee5a9635cd7
- bb8497b5cf575e3a
- d97244a589ca587f
- 8af2a66435ea565a
- 37e2bc0cb5a053a5
- a6be7050ff205933
- 6704953640e55b83
- 8a880b6ff1dd59ab
- f68fcc74e570541d
- c5ec810bb3625418
- 6c9e40634f705f56
- e10bd715492150e3
- 2497e961a13e50f8
- 17c882b28a195c3d
- a4fb656f624e5458
- a547f498303e5b17
- 22dde440a0c35d31
- 134b10cfe7e753e6
- c772799eaf1f5ad1
- 9d1bd4fa169c5ebe
- d21b22d6c0405ad7
- 3862c9ed94ab5f90
- fc4bdb76d30553b0
- b1b2eb47b045566c
- fa7793ced9cc559e
- 5930f153954b5060
- 324cb0d226a45b91
- b619e01b47775ec5
- 7ccd759aa0535b9a
- 81a473b817565cb9
- ed1ae68f8c0f5f3a
- b65dbda85d085330
- 669972d5c4c55872
- 3502b30911d75ed8
- 98e3abe2a38c5156
- 63fd66d1098f5c53
- 8c9e3fd944c051e3
- 09436f14d3185748
- eb19160d56255b73
- ffb2d865d42e57c0
- d44241b93dc95d36
- f0a6222ab3e55174
- 530176929c015182
- f6082f18c392582f
- 7e76a2b3918656f9
- ba7553f511f653b3
- 5f09eaa4509f5997
- 8a3c6c3502035e11
- 664106f910475a53
- a9e8e0a755d758a1
- b2229456008c518d
- 3e4c9c9e67545b03
- 69124bf1a9185f06
- 5c872773198c5689
- e56402797d665711
- 76b1b05efba353fe
- 129c4e6b058a5f6d
- e933d70dd378598f
- e2a0ac6a977b5c70
- 62aefe5efb00563f
- 58f3f43098985e77
- 9a4575e2dfd75ffb
- 9d864c15bf7d5414
- db4bcafb6d775b4f
- 14d9640a8b9d5d7d
- 5a8a6c9d92935076
- 8647866881f3587e
- 406f8b299de35ce2
- 73471e4908bc5708
- 095042ae1f985c39
- 490463fd7e9e5769
- 0ddc071278375700
- 8a492ff6a81054a7
- 0855e09733fe5445
- 7bcc91de36385afe
- ed205afc48d150f3
- 36aef5f67c8d5e2e
- 2c71b83e25e1577d
- 4d2885661a535f9b
- 8ddb6763987051ba
- 74d72b3cd99d5ab4
- 66583dab627951a2
- 63980d0b4c9352c4
- a2c2e046132e5596
- 6360aa4dd01151c3
- 9c2063a3e137542a
- b113e988ede45a4f
- 8d06ea883e7853a9
- bcf92cdb596a5fa2
- d577027e9c295bde
- 213870b088245664
- 9e9e33077f375062
- e8daa33268685b31
- 3346340e1c275766
- 420d59a27cb053ae
- ab0c43fd9f2c5481
- 26b5e3878f2250ac
- 0b0a419d29cf5e9a
- 078bc1027dde5d1a
- 4376d00ed2245c21
- 8fdb21d863c5504b
- c4884a363f805a18
- 515b2946ba2457b5
- 324f93888ec35bb2
- 250389f21dee5793
- 4161016e65df5b37
- 583e9cc4115258e4
- 742456f4f1c65425
- 7316c116f05d57a5
- 671da9103fe05141
- ee91209e45fe5141
- 6cc0563c1a0d5c3a
- 5806eb348e3250d9
- f6d575d8e0a45772
- 815565a62f775c7c
- d14ccafb937a543a
- 173369dc059d5fe9
- 94a3b8d43f515d6e
- dcf6caabbee354f7
- 3d04f4c65587562b
- bb7aca330b2c5ac2
- faba362f85a95b6c
- 5ec473ffad5c55ba
- 40726c708b17504a
- a9ffe9bb174851e6
- 80722f66bc3b54c0
- b4bcd9085faf5842
- eb15f0d956eb5ac4
- 9ca89d773ed651ab
- ad5284a6be715f10
- bacbab3d771e59fd
- bf1184622f355af4
- f66d06ec0f355fac
- 47f29dad0bec52d2
- 36899d67473c5c91
- 39a769c19105586e
- 277758d55617567b
- beee170c9d8159ad
- 313a7a6feb1c5490
- e1540b19efec5d97
- 55bb551a2aa85849
- 2743a2f96269577c
- 8d7c5f26b9775cce
- dd414d3d7d5452f1
- 38ecbc57db7e561c
- b0bd81048c07524f
- 8d8f5c8c6c29525c
- 04703c86cf5b5a20
- 6c578cebcf47592b
- 77ebf0edb75c5b69
- 2b7bf25209dd5705
- 7077e840fef95b8f
- b0b461ce7bd959ec
- 907f2c5fde6f5db8
- 150bfebecc525d57
- 0a6e90cccbb15213
- 48e9a54281845595
- 02015675e4585611
- 657274955033592a
- cb5022a3bef557e3
- f409dfb714ed539c
- e31131deed6656ea
- 17bc4c71fc425620
- 8f60912c624e5f5f
- 9cf612ff6e4f5bd5
- 472899393e8f55e1
- a5d356da90d05835
- 447a983c9fc45077
- 490f13844af5590d
- afe3f2650ff85a95
- 715d1ae75d215269
- 3c3991ec8d7a5507
- 9b0f5a2f65e45867
- e2ae05340dba502d
- 87c6ef5053865368
- 71af26e14ba65545
- 613c91adcbe55cd5
- 7956c9ed4b855859
- 655c3f17ee2d5683
- 38a5d409f1095059
- c0fb4281da785582
- 11bf2d4580ab5bc2
- 7f9f4661a4875959
- 34ac200e359653b5
- 7fc551e4e0375d00
- '7335659408525112'
- c65ad538a2275dd8
- 3068d16e627b5e69
- 3f31d5d096f957c9
- 01876d7aa6f55554
- 5c4d8dfcb0aa5541
- 5041cdf76ecb5ee7
- 26de9e2da40c5b0c
- 62974364debd5463
- 7956fe13f69e53dc
- 94c0ff5134d45dd1
- b90086e468f05378
- cd58499f8230591a
- c67e9184504951c5
- 012432bd62b85f80
- a689d4a215245104
- 28cd9541bc35593f
- 4cee76c8118b5609
- eb86e67498595966
- 57177f12c7045c13
- 4aab1b32b1ad58aa
- 5c46c17f514b5153
- 83671631057f50a4
- e26d9a5288165f2a
- a51ed55eaa9c54c9
- d6f52d0bbaf5523c
- 4a46ef99ddf55b8d
- 7d4c548895955e0d
- e721852571e5573b
- 901b2d48b2ce5bf1
- b15b2d36b1ea51cc
- f8bec974b86952e9
- 6eac1c0e2bbd57bb
- 54ae4b189e79541b
- 0f6aef2cc48d5621
- 3fdefe546f3159fd
- 1d1dde59c417522f
- 69e8fff107b05199
- 6cbc045e25c2506d
- 47c92818d9005eea
- 5e74b6a61b715f47
- 03d4ec82e7ac5804
- ecd769043adc5346
- 68e2e4227c355dd9
- 0f8e3ba3d90958d1
- 4ee4ab24a93f5375
- 508511fd38a15d52
- 3c114912e4cf590c
- 9fc65b945c175ebb
- 7e5925fce8df5e44
- 4e2cc4b2c43055fe
- 89e02236312d5038
- 92778c3bfcda566d
- b8e377d0f7b95014
- be709e9a5d085f75
- c82bebed0dac5691
