_target_: navsim.common.dataclasses.SceneFilter
_convert_: 'all'
num_history_frames: 4
num_future_frames: 10
frame_interval: 1
has_route: true
max_scenes: null
log_names:
  - '2021.10.05.07.49.39_veh-52_00934_01406'
  - '2021.07.09.02.42.50_veh-35_00038_02629'
  - '2021.07.09.17.06.37_veh-35_02609_05015'
  - '2021.10.11.08.31.07_veh-50_02360_02684'
  - '2021.06.09.17.37.09_veh-12_04489_04816'
  - '2021.07.09.16.12.19_veh-26_04434_04498'
  - '2021.10.11.08.31.07_veh-50_00282_00680'
  - '2021.06.14.16.48.02_veh-12_04783_04967'
  - '2021.07.09.01.37.16_veh-26_01726_01793'
  - '2021.10.01.17.52.06_veh-28_01034_01107'
  - '2021.08.17.17.17.01_veh-45_02098_02251'
  - '2021.10.06.17.08.46_veh-28_00498_00621'
  - '2021.08.31.14.01.15_veh-40_00573_00681'
  - '2021.09.15.12.32.43_veh-28_01070_01157'
  - '2021.06.14.14.25.15_veh-26_04542_04617'
  - '2021.07.16.01.22.41_veh-14_04315_07102'
  - '2021.07.09.15.53.28_veh-38_03528_04262'
  - '2021.08.24.17.01.06_veh-45_00228_00689'
  - '2021.06.14.13.27.42_veh-35_02283_02603'
  - '2021.08.24.14.35.46_veh-45_00011_00162'
  - '2021.10.06.17.43.07_veh-28_00508_00877'
  - '2021.06.14.16.32.09_veh-35_00283_00357'
  - '2021.08.24.20.03.01_veh-45_00824_00888'
  - '2021.08.31.13.27.52_veh-40_00688_00750'
  - '2021.06.23.22.05.48_veh-16_00015_00276'
  - '2021.06.14.18.42.45_veh-12_03913_04017'
  - '2021.10.01.19.16.42_veh-28_01511_01624'
  - '2021.09.15.12.32.43_veh-28_01513_01697'
  - '2021.06.09.14.50.36_veh-26_01782_02044'
  - '2021.08.17.13.15.12_veh-45_02304_02650'
  - '2021.10.06.19.27.33_veh-28_00016_00079'
  - '2021.09.15.13.52.55_veh-39_01385_01446'
  - '2021.06.07.12.42.11_veh-38_03254_03455'
  - '2021.08.17.14.32.33_veh-08_00521_01051'
  - '2021.08.17.13.15.12_veh-45_02025_02103'
  - '2021.06.23.14.54.32_veh-16_00636_00840'
  - '2021.05.12.23.36.44_veh-35_01735_01957'
  - '2021.07.16.18.49.56_veh-26_00256_00822'
  - '2021.06.14.14.03.45_veh-38_00780_01007'
  - '2021.06.14.16.32.09_veh-35_01219_01415'
  - '2021.06.09.17.23.18_veh-38_01151_01532'
  - '2021.09.14.19.46.05_veh-45_01937_02119'
  - '2021.07.16.22.40.23_veh-38_00016_00182'
  - '2021.10.05.07.49.39_veh-52_01417_01574'
  - '2021.06.14.18.13.35_veh-26_00385_00471'
  - '2021.10.06.17.43.07_veh-28_00302_00486'
  - '2021.10.06.17.43.07_veh-28_00933_01014'
  - '2021.06.14.18.42.45_veh-12_01345_01523'
  - '2021.06.14.18.33.41_veh-35_04275_04435'
  - '2021.07.16.18.06.21_veh-38_00016_00747'
  - '2021.06.23.16.52.00_veh-26_01043_03099'
  - '2021.06.23.18.23.38_veh-26_00663_01217'
  - '2021.06.14.13.27.42_veh-35_00353_00531'
  - '2021.06.14.18.42.45_veh-12_02099_02167'
  - '2021.07.16.18.06.21_veh-38_01526_02150'
  - '2021.06.08.12.00.19_veh-35_05235_05578'
  - '2021.09.15.13.52.55_veh-39_00371_00631'
  - '2021.06.09.19.40.26_veh-12_01525_02020'
  - '2021.06.14.18.42.45_veh-12_02233_02300'
  - '2021.06.14.14.25.15_veh-26_04936_05073'
  - '2021.05.12.19.36.12_veh-35_00215_00405'
  - '2021.06.09.18.23.43_veh-35_03403_03481'
  - '2021.08.31.12.54.56_veh-40_00921_01014'
  - '2021.10.06.13.21.47_veh-28_01755_01829'
tokens:  
  - '6db4868738c25921'
  - '5ab2282dc4a356c6'
  - 'c31674941f9b51b5'
  - '2fb17d18ba345719'
  - '03f6cbb970625cdc'
  - 'aecfe3d39819549c'
  - '7b9e548ccad85bda'
  - 'd73caeda671c5bf6'
  - 'bfd581e323575342'
  - 'bd6ee0731bb85e2e'
  - '450bc8da25a6559b'
  - '7354f11efe5954a0'
  - '890a7926e2c65194'
  - '578a1e9f0dda5abe'
  - '14841da557075390'
  - 'bc4345e13302535e'
  - 'faf7768564275cab'
  - '93e51bc61f9e5719'
  - 'e0f645fd3d865aba'
  - '70510964a22e520d'
  - 'c4f57852a9f75299'
  - '38f63f16580d5180'
  - '3283779184b85c5c'
  - 'bd1b5ee8e45c54d5'
  - '3e93502886e45d12'
  - '24373cf8018e5998'
  - '043c36131804518d'
  - '7be0308c03c55e85'
  - 'c4ddc9d6799251d7'
  - '4660fe44e77557a1'
  - 'f5ce75e7e1375fda'
  - 'f1dba8e226145ed9'
  - '6e054e6e2b7752c0'
  - 'dc0566595d2b53d3'
  - '48ed23638a29595e'
  - '7c81e37172385d78'
  - '9a6ed5eaffeb506a'
  - '95a2527a0ce45c5b'
  - '8a0928ddd1cd58aa'
  - 'f155b91c60b95478'
  - 'ea88691d56585dd5'
  - 'cc520ea61d7a5704'
  - 'e6059049315a58c7'
  - '8150c358146357de'
  - '73194863d0475684'
  - 'b3eea6b54e5e5433'
  - 'cb17093462855ce4'
  - 'ba9b27468f635313'
  - '7807f1ea3d905e8b'
  - '467431a5ec1954d3'
  - '9d7cdb0e4461565e'
  - '0890bb5fe73659d7'
  - 'fa0aa8a028125817'
  - 'af08d2600ca05c87'
  - 'f1f801395d845872'
  - 'b0a5a039d36c51a3'
  - 'c6a83a1510f855f8'
  - 'd930e4e72dd75d13'
  - '1be40c92b4f5558f'
  - 'fa48402c023c504a'
  - '46e906ce8393575e'
  - '3d72242a7b365ac5'
  - 'dc0ace60208d57a0'
  - 'cf9a09381e7952fc'
  - 'c82951e08ea7566a'
  - '9bb6c339a7f95e6d'
  - '6ccb559cd2fd5a82'
  - '42976cf4b5dd5eb9'
  - '863d56e59983567c'
  - '17c08fd8834153f7'
  - '3c566e990fb35c0e'
  - '10133719351f5661'
  - 'ed56123513f65904'
  - '25086095a8b256f8'
  - 'beb5fc7652755542'
  - '466d250f4f83528e'
  - '9fc121e8694a57f2'
  - 'b1bb0a4c8a5f5bee'
  - 'd77c0dc5e2fb5366'
  - '09b6b5fd058f5512'
  - '577507d0ca285811'
  - 'b5a417f2def455bb'
  - '6febee07a44a5f0b'
  - '08bd7e8401255362'
  - '1423b02d8dda5f20'
  - '042727362a4c5a87'
  - '86053e512789532a'
  - '188815fe18815432'
  - 'aa8aecb02c715fd8'
  - 'be9066fa8c2e521d'
  - 'cb0b42036c615dd5'
  - 'a04ef66908a957a3'
  - '06e1e59df57f5f06'
  - 'f3b6258813e15ebe'
  - '6f07bab67981599e'
  - '0ab6d00e5b215474'
  - 'a30da804fc155772'
  - '5b89a51d8cd953ba'
  - 'e9da1c3486c057a9'
  - 'a986cdfc4dd450b9'
  - '7538b734110b5b1f'
  - 'fc70fbd002b75c16'
  - 'c37c94fa634f5265'
  - '66914505feb756cf'
  - 'f2acbaf09a6b5840'
  - 'a9820a2990d659d1'
  - 'abd18b5a97c657f4'
  - 'ad85bd9d71e35299'
  - '6283ecf42a7a58cc'
  - '8cb18e17d48556af'
  - '851e947a554c5b78'
  - '6a2761ac326e5b26'
  - 'ee235d2d4194539c'
  - '21edfe16926b558e'
  - '4a55f54c78365c9a'
  - '970ca65f85e7570d'
  - '730943087afb5135'
  - '5e8192e33ccc53a8'
  - '01c8a1a2709259e0'
  - 'cfdec0828a795277'
  - 'ff26614297fe5a29'
  - '72ff988087705d96'
  - '2f0fabe29f365b49'
  - '6a825b14edfa59e3'
  - 'd82d07ac01e1585d'
  - 'e359964f5def59f4'
  - '8fc54421e7f85555'
  - '391aa78401a25ea0'
  - 'f113b1f7547f52d2'
  - '39750b584853541d'
  - 'df69e3183ffa5d51'
  - '1b032e35d5775045'
  - 'ab0902d66e2a5115'
  - '4275c32123e55a9f'
  - '247da1feaa0f5437'
  - 'e6a85ef20b3054c4'
  - '631cfa1f7f56535b'
  - 'f965e8fe00975c29'
  - '9069684898175278'
  - '249e3c46e4145078'
  - '383d78e45e84565a'
  - 'e9298e4393bf527a'
  - '21cff006a9565439'
  - '7621cff075dd5ab0'
  - '0df3ad159e8d5778'
  - '2ec0a8820d1259e4'
  - '6e8a030b97835684'
  - 'd200bd5109a159b7'
  - 'cf7d520744025570'
  - 'c9ba6bd6e2515f52'
  - 'f7f924fecd7c577a'
  - 'f051035873065a02'
  - '7b43a5025a5a5113'
  - '0d96ec5d891b558c'
  - '7ebe20acb9535a35'
  - '73a5f6856c1f50f6'
  - '0c47bfc26ed55b85'
  - '62f5776581dc5a52'
  - '6ad2c73dd6e956a4'
  - '4931e695ff025fcd'
  - 'ca1bf120ab8d5259'
  - 'ab1b0596a52f51e5'
  - 'e615ff0a202551bb'
  - '9859fca9139a54a9'
  - 'ed8db17d43175a7f'
  - '7310a5f97dc15411'
  - 'eb3beff4cdab5513'
  - 'fb8c5bef1d3a5cec'
  - 'c8e0e57479a25a43'
  - '4b9573b1ca6150a2'
  - '4e40a890bb4e5389'
  - '78b314a1dfeb58d6'
  - '98082617824750ed'
  - '94343795ca3e519b'
  - '20ccbc0755d05dff'
  - '42d3b668ce215c90'
  - '84824ec3b3ff5e01'
  - '3a6fe1ac706959d5'
  - '6b9291ce4e725b55'
  - 'ad543c2c30dc5ed8'
  - '44646d00f796544c'
  - 'e4456fbafc6b529d'
  - 'da0a29ca87de5da4'
  - '18483748075d5076'
  - 'bbd80f5e88a9525f'
  - 'a07dee86ce3b5eab'
  - '82e0b9c701f25f60'
  - 'c39663a19c945531'
  - 'd2355815821358da'
  - '7855a2d2c1e154fd'
  - '64b9bdabd31e5a10'
  - '05cd45426dd55fb6'
  - 'bc77850a6cf95616'
  - 'e2681746065a5177'
  - 'c0368108e97150ae'
  - 'adcb6d280e365876'
  - '95908240498a5392'
  - 'bbceeafa6b365166'
  - '81fc91e0093a527d'
  - 'fef6e56ccf645a85'
  - '152072a59b205963'
  - '69ba11bc8e8b52f7'
  - '02837c3e17b450a2'
  - 'b0b1abf3002b57f1'
  - '3d8d34ee0cb65dd4'
  - '18b38d79205e570a'
  - 'c5d1364d4b865d91'
  - '295e2803cbd15ccf'
  - '624c51a38b485b58'
  - 'f1ea9339494255ca'
  - 'a360485d54cc5257'
  - '6b24438aa440536b'
  - 'c9e867e031055605'
  - '5f39e78b820d52f9'
  - '4a7161a9c7095984'
  - 'c7a8bf9fe2935dc6'
  - '4be812f7a3975df0'
  - '666b703eeba55821'
  - '3e4bd8b0843c5092'
  - '158d4052162f5414'
  - 'edc860d5d1485932'
  - 'f3560a755888508d'
  - '0a88caafd9665083'
  - '3dcb1fd2910d590b'
  - '5064e21117b25126'
  - '9c267aea99365272'
  - 'f593749a2fce54b2'
