_target_: navsim.common.dataclasses.SceneFilter
_convert_: all
num_history_frames: 4
num_future_frames: 10
frame_interval: 1
has_route: true
max_scenes: null
log_names:
- 2021.06.03.12.02.06_veh-35_01100_01227
- 2021.09.09.17.18.51_veh-48_01462_01552
- 2021.06.28.15.02.02_veh-38_02398_02848
- 2021.06.03.12.02.06_veh-35_00233_00609
- 2021.05.25.15.59.03_veh-30_04027_04200
- 2021.06.03.13.55.17_veh-35_02572_02855
- 2021.09.16.13.53.10_veh-42_00180_00342
- 2021.05.25.14.16.10_veh-35_02482_02649
- 2021.09.29.14.44.26_veh-28_00238_00320
- 2021.05.25.14.24.08_veh-25_04059_04203
- 2021.05.25.17.54.41_veh-35_01654_01850
- 2021.09.16.15.47.30_veh-45_01199_01391
- 2021.05.25.14.24.08_veh-25_00934_01067
- 2021.09.09.18.29.25_veh-39_00969_01184
- 2021.10.06.08.16.17_veh-52_00922_01296
- 2021.05.25.16.37.23_veh-25_00005_00217
- 2021.06.03.17.06.58_veh-35_03860_03992
- 2021.09.16.13.53.10_veh-42_00860_01069
- 2021.06.28.18.03.27_veh-14_00620_01581
- 2021.09.16.16.20.27_veh-08_02435_02525
- 2021.05.25.18.38.25_veh-25_04058_04186
- 2021.09.09.17.18.51_veh-48_00574_00646
- 2021.06.03.17.06.58_veh-35_00712_00855
- 2021.06.03.13.55.17_veh-35_00073_00426
- 2021.09.16.14.39.34_veh-42_01609_01687
- 2021.09.09.17.18.51_veh-48_01173_01237
- 2021.09.09.18.29.25_veh-39_01622_01766
- 2021.09.29.18.19.40_veh-28_00844_01218
- 2021.10.06.08.16.17_veh-52_00181_00574
- 2021.10.06.07.26.10_veh-52_00772_00917
- 2021.09.09.18.29.25_veh-39_00569_00903
- 2021.10.06.08.16.17_veh-52_00032_00170
- 2021.06.03.18.47.39_veh-35_00503_00777
- 2021.05.25.14.16.10_veh-35_01100_01664
- 2021.10.06.08.16.17_veh-52_01590_01725
- 2021.06.28.20.24.43_veh-38_00369_00601
- 2021.09.29.14.44.26_veh-28_00528_00992
- 2021.06.28.15.10.57_veh-16_02438_02580
- 2021.10.06.07.26.10_veh-52_00953_01126
- 2021.10.06.07.26.10_veh-52_01245_02064
- 2021.09.16.19.49.00_veh-42_00990_01609
- 2021.09.29.15.23.04_veh-28_00601_00802
- 2021.06.03.13.55.17_veh-35_02419_02561
- 2021.09.29.18.19.40_veh-28_00331_00426
- 2021.09.16.19.12.04_veh-42_01438_01677
- 2021.08.30.13.45.25_veh-40_01116_01336
- 2021.09.09.18.29.25_veh-39_00427_00556
- 2021.09.16.14.39.34_veh-42_01111_01448
- 2021.06.03.17.06.58_veh-35_02943_03220
- 2021.09.29.19.02.14_veh-28_00540_00917
- 2021.06.28.16.29.11_veh-38_01415_01821
- 2021.09.09.17.18.51_veh-48_00657_00876
- 2021.09.16.19.27.01_veh-45_01749_03230
- 2021.05.25.14.16.10_veh-35_04097_04328
- 2021.09.16.19.27.01_veh-45_00472_00711
- 2021.05.25.15.59.03_veh-30_03499_03671
- 2021.08.30.16.16.44_veh-40_01099_01351
- 2021.09.29.19.02.14_veh-28_02911_03005
- 2021.08.30.13.45.25_veh-40_00878_01104
- 2021.09.16.19.12.04_veh-42_00289_00398
- 2021.05.25.14.16.10_veh-35_00083_00485
- 2021.09.29.18.19.40_veh-28_01727_01833
- 2021.09.09.17.18.51_veh-48_00098_00328
- 2021.09.09.14.18.22_veh-48_00221_00299
- 2021.09.09.18.04.06_veh-40_00555_00731
- 2021.09.16.15.12.03_veh-42_01037_01434
- 2021.06.03.13.55.17_veh-35_00789_00999
- 2021.06.03.18.47.39_veh-35_00257_00492
- 2021.09.09.17.18.51_veh-48_01248_01450
- 2021.09.09.14.18.22_veh-48_01298_01492
- 2021.06.28.13.53.26_veh-26_00492_00696
- 2021.05.25.15.59.03_veh-30_04463_04606
- 2021.08.30.16.16.44_veh-40_00779_01088
- 2021.06.28.16.29.11_veh-38_03263_03766
- 2021.09.16.14.39.34_veh-42_00297_00935
- 2021.09.16.13.53.10_veh-42_00077_00153
- 2021.10.06.08.16.17_veh-52_01949_02501
- 2021.05.25.16.37.23_veh-25_03311_03550
- 2021.06.28.20.24.43_veh-38_03385_04952
- 2021.09.29.19.02.14_veh-28_00964_01689
- 2021.09.29.14.44.26_veh-28_01331_01485
- 2021.09.16.13.53.10_veh-42_01510_01591
- 2021.06.03.18.47.39_veh-35_00123_00246
- 2021.10.06.08.16.17_veh-52_01430_01579
- 2021.09.29.19.02.14_veh-28_00273_00514
- 2021.09.29.19.02.14_veh-28_02451_02708
- 2021.10.06.07.26.10_veh-52_00422_00728
- 2021.09.16.13.53.10_veh-42_00630_00818
- 2021.08.16.14.23.37_veh-45_00015_00132
- 2021.08.30.13.45.25_veh-40_00784_00867
- 2021.09.16.19.12.04_veh-42_01088_01192
- 2021.08.30.14.54.34_veh-40_00439_00835
- 2021.09.09.14.18.22_veh-48_01503_01761
- 2021.06.28.16.57.59_veh-26_00016_00484
- 2021.06.28.21.47.53_veh-35_00280_00424
- 2021.10.06.07.26.10_veh-52_00006_00398
- 2021.09.29.15.23.04_veh-28_00814_01101
- 2021.05.25.14.26.37_veh-27_04122_04279
- 2021.09.09.18.04.06_veh-40_01340_01425
- 2021.05.25.14.24.08_veh-25_03764_04034
- 2021.05.25.17.54.41_veh-35_01905_02121
- 2021.09.09.17.18.51_veh-48_00889_01147
- 2021.09.29.14.44.26_veh-28_01509_01628
- 2021.05.25.15.59.03_veh-30_00625_00855
- 2021.05.25.17.54.41_veh-35_04967_05098
- 2021.09.09.18.04.06_veh-40_00743_01071
- 2021.05.25.17.54.41_veh-35_02723_02902
- 2021.08.30.14.54.34_veh-40_00885_00986
- 2021.05.25.15.59.03_veh-30_01478_01643
- 2021.05.25.14.16.10_veh-35_01690_02183
- 2021.09.09.14.18.22_veh-48_00322_00895
- 2021.06.28.16.29.11_veh-38_00022_00368
- 2021.09.16.19.12.04_veh-42_01221_01380
- 2021.08.30.13.45.25_veh-40_00610_00771
- 2021.09.29.14.44.26_veh-28_01059_01191
- 2021.09.29.14.44.26_veh-28_01640_01743
- 2021.09.29.19.02.14_veh-28_03198_03360
- 2021.08.30.14.54.34_veh-40_00334_00419
- 2021.09.16.14.39.34_veh-42_00032_00186
- 2021.09.29.14.44.26_veh-28_00337_00504
- 2021.06.03.13.55.17_veh-35_02866_03582
- 2021.06.03.17.06.58_veh-35_02571_02742
- 2021.10.06.08.16.17_veh-52_00612_00782
- 2021.09.29.19.02.14_veh-28_01717_01824
- 2021.06.28.21.16.05_veh-14_00957_01198
- 2021.09.29.18.19.40_veh-28_01268_01685
- 2021.09.16.17.40.09_veh-45_02539_02745
- 2021.09.09.14.18.22_veh-48_00960_01115
- 2021.09.29.14.44.26_veh-28_01202_01296
- 2021.10.06.07.26.10_veh-52_02208_02394
- 2021.09.29.18.19.40_veh-28_00438_00833
- 2021.06.03.12.02.06_veh-35_03526_03712
- 2021.08.30.16.16.44_veh-40_00256_00716
- 2021.09.16.21.13.37_veh-42_00172_00347
- 2021.05.25.17.54.41_veh-35_04111_04288
- 2021.05.25.14.16.10_veh-35_03373_03550
tokens:
- 8d9d0d3caa9b5905
- 91defa409f0254d5
- 9a23e7bc52e657c3
- 090af86f693c507b
- cc6022c226c15d80
- 91ae20bf459859fe
- 68188bae28595f7c
- ee545028f8a85e6f
- fb643a2514195bfa
- 963a72ef9c615033
- 1b736bfe747b5987
- a0e9cbedca0a56b7
- f038fc7ffdab5bad
- 5fe951e403f25012
- 2d9d1d9aa6d25bd9
- c53ae2fe6cc751e7
- 5fed3ec5ed1351c1
- dcf6caabbee354f7
- 09babda49aa659a1
- 6a8571daa3445923
- 9ef1d618435d5e53
- abe4fa26de85552d
- 40a69dc4d1f854a8
- bbd85b27fa465894
- 38a5d409f1095059
- c0fb4281da785582
- d780d3a3f10d567b
- fbe786c417ca5245
- 14fe69db03425780
- a75ca6ddabc1541b
- 82e84851ea985ba8
- ae90dd8267ce57a0
- 4f47f41d84c450e8
- e1d83d0f913a5263
- 0df7b61597705cf2
- 14743d928b9257a1
- 21acd3bbf97b5cbe
- 53f754a75b955383
- 075154c90a0a5d7c
- eff63ffe642d5409
- fb7d83b69f38539f
- 129c4e6b058a5f6d
- cf1ad202aadb5ee6
- b5a8b9b436b05bad
- 761d3f2365c25886
- 0e479a9039ef5c10
- 1d95772619d35606
- b619e01b47775ec5
- fcb157cfb7785486
- cbc47540cc665da4
- f35274c7a16657d7
- 673a88a4037f5b6b
- a7cf529d15425b63
- cc86bfa114035604
- dcd5dc3f53d9533f
- 521247f86d7f57c0
- 9d21f2742b1a5b27
- 364dd4c7c4cf55cb
- 260d0c0225eb534d
- f78a67043d9e5477
- 4bc96604c1c85606
- ee91209e45fe5141
- dd79f9aa92105761
- 6d66b095f93750f7
- 0a08850db6e35ab7
- 00c489998dd4555c
- 2d7bc87644e85744
- 70d79606f745562e
- 135337bf847b5726
- 431869f33ace51a0
- 2c1f43c6b93c5952
- 28d8f3699547568b
- bb85e87e90ae52ec
- d4ac0a1865ac5c25
- 30d10a9c1f8352da
- 9aad3780bef85c98
- fab7537b12d254bd
- 92106b8512315c03
- 5aae47691f185a21
- a075b9f46b7b5831
- 7f2934ac111854f5
- 9972c06c954b5770
- a1e689b17ca65053
- b42b3012c31c5b03
- 206322cf0cf45186
- a780d35138495c38
- f99992756cbb5adb
- df36523fdaeb5882
- 9fa75f1d5863570b
- df240e44ad0d5c3c
- 345f39f8de925db9
- da36c99454f65715
- 689abfdd66235378
- 11650e6f32715f8f
- 21e98ee0ac165e2c
- e56f85ee56395a99
- 0d74b112df715917
- 8cee2a96b57d58ba
- 6b52f2b62f215cb4
- 93b93c0235375b93
- f47841466d835000
- 302803d07e7059dc
- 11c529f1623b5034
- 113d448b6ea8555c
- 2d9d3d15e7f25716
- ef703bb40b9a516c
- 1a928640315c5332
- 84431cd14c765efc
- 2c14c850f6645147
- aab44cff9f3552b1
- c6be203c41a155e4
- b031a0b55ab951f8
- 5583c1447acd5f31
- 34ac200e359653b5
- 1e91e4b9af695706
- 7fc551e4e0375d00
- 43fe2321124251d3
- f42c66a9b7a456f7
- 3a31f6e6819d5ab2
- 8237f47b224952b4
- e61adc75d7da50c3
- 017e89f6f6a85d79
- 13310ca9a7715154
- f2655b7cd5d15a20
- 8bd32ab85e615190
- 308e246a1d995edd
- 6561633171e75bb6
- aba7212ffa3458b6
- e6c36a6be3c75127
- ac808bd1bfac5425
- 32a19a2ab50f563d
- 31e7be6258f35c5a
- 5c838efd36805c92
- 008b419a63b75917
- eba929a6772254e4
- c823f9a693a05d93
- dd4e7db697465be3
- f6c6b09c85e357ee
- 7964bed69f7e597e
- 8b7722d516e553ba
- b841de24ffcb5c87
- a009893e14c75fd0
- 5d78f0d383a95860
- 3380ae828ea75d1e
- cdf234c4f4c35156
- 54d86279a0015154
- 78beb0eba954535e
- 595909c413ac56dd
- 7c04e29efc0c5e46
- 3128b8da22c75dd0
- 6b97412307ad5c16
- e747d6fdc59252f3
- a8d4a3fc503c5f83
- 985af967de8f5f3f
- fe9e76e6cac35fba
- bdad96248e575296
- 8239fb2f8d705dea
- f1bd1724d07957cc
- 932938d86cfc5d6f
- 7aed9edff97256c0
- 6d4f69f0aabc5c4e
- 78cfb731b49c5aed
- ef7fb2d0c7bf52a4
- 9b0f5a2f65e45867
- 542bec9a7d6e5c52
- 4abb45d9ee1a5c5c
- 1981a85eb4ba5001
- f3512ae175b45844
- cfb755b8d37458ac
- d142ab856b7653df
- d534aec3a5085c3b
- 767ce55e55515539
- ffed00245f3f5d00
- e88e44d720f65e0e
- 9ab5654cfc9f5724
- 18973046d1215390
- 666e41a5d36c50cc
- 1fe2f21f53c05378
- cf693fb497155dee
- 8eb6e6b220755d3b
- fde793c65573590a
- 29c3b3019c9e535a
- f642f93db71f5dfb
- 020ba7462c6f52b3
- 58a10d0c924050cf
- bd5e1c226cca5d3e
- ebffacdb3be25252
- 9ed452bde7335185
- 4fd0583319865636
- 1e1913cd8d035225
- 2be2e48e80985bee
- 17a015f4ef9b56d0
- cfc9186dc53b5d4a
- 8f8ccbd6ffcb54b9
- f2a41314d1575761
- 69baa41122b45e43
- c5510354351d5d5e
- 2f421d857f32510e
- a99338e1112e5f65
- decd6b1dd7f65e1e
- 2d365fc1fbd35aab
- 1b65613f0242544a
- 43761f0721035214
- 70d9d518ad0f5382
- 82226888c99e531c
- be7c407443f15fec
- ead04653ed0c5545
- d70f77951917593a
- d514826bdd045d68
- 60c9aabf696a5756
- de9dd93857cf5ab5
- 0beacadfbc4553ea
- 6363aa6d3d715e03
- cbcd554895c75231
- d852a7b32d6c5448
- f21d5b2f9a5e5276
- 333a4f8a12dc564d
- 0e81b2ebbb30575e
- bf1184622f355af4
- f94d84bd174d59ce
- 0e04335474bf5b6e
- e6dc564e1a3a588e
- 40e774c643fc5689
- 7cf4a1ba9b6054f9
- 38f5cc0699195554
- 27c0f4e2b49b5c08
- cd58499f8230591a
- 2e34ba0896d75c28
- c5e4f3c361b252c1
- c67e9184504951c5
- e63b6dfddfc855da
- b031e4b0aea8528b
- 7727bf26f5845499
- e530e78499a75539
- 012432bd62b85f80
- 65a5be18fdb7508d
- 7eb4ec2ae9fe5702
- 82551627c2415e8e
- d5a79b89fb985129
- fbf9670a3e82519c
- 12f5053055935463
- 6b68c09f87b85dc8
- 39fde97003dd540e
- a9af1e73c9575428
- 409711b03072566a
- 5f859ab2a2205477
- 225eb6e22af55972
- 7feaf6410f1854a8
- 3b0c5c39455b5d00
- ccdb6840a0445870
- 7b2f3235b4cb5374
- 662cb541b8db54a1
- 196cb93444b35dd7
- ccd53fdd1b6e51b8
- d6b5646287065fa8
- d9422fc7065e5b62
- aacc2ed7ba2859c5
- 33a43f22312c570d
