_target_: navsim.agents.dp.dp_agent.DPAgent
_convert_: 'all'
pdm_gt_path: ???

config:
  _target_: navsim.agents.dp.dp_config.DPConfig
  _convert_: 'all'
  seq_len: 2
  ckpt_path: dp_ckpt
  lidar_seq_len: 4
  sigma: 0.5
  trajectory_imi_weight: 1.0
  scheduler: cycle
  progress_weight: 2.0

  normalize_vocab_pos: True

  camera_width: 2048
  camera_height: 512
  img_vert_anchors: 16
  img_horz_anchors: 64
  backbone_type: 'vov'

#  camera_width: 1024
#  camera_height: 256
#  img_vert_anchors: 8
#  img_horz_anchors: 32
#  backbone_type: 'resnet'

  vit_ckpt: ${oc.env:OPENSCENE_DATA_ROOT}/models/da_vitl16.pth
  intern_ckpt: ${oc.env:OPENSCENE_DATA_ROOT}/models/intern_object365.pth
  vov_ckpt: ${oc.env:OPENSCENE_DATA_ROOT}/models/dd3d_det_final.pth
  lr_mult_backbone: 1.0

  trajectory_sampling:
    _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    _convert_: 'all'
    time_horizon: 4
    interval_length: 0.5

checkpoint_path: null
lr: 1e-4